### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by edgarrmondragon** [MeltanoLabs/tap-mongodb#42]
```[tasklist]
### Tasks
- [ ] Set up trusted publisher on PyPI
- [ ] Set up `pypi` environment in this GitHub repo, with some permissions
- [ ] Use VCS versioning
- [ ] Add a build + release workflow
- [ ] Publish
- [ ] Update MeltanoHub
```
